create INPUT_TXID INPUT_VOUT OUTPUT_DESTINATION OUTPUT_AMOUNT:
  #!/usr/bin/env bash

  set -euxo pipefail

  bbqcoin-cli createrawtransaction \
    '[
      {
        "txid": "{{INPUT_TXID}}",
        "vout": {{INPUT_VOUT}}
      }
    ]' \
    '[
      {
        "{{OUTPUT_DESTINATION}}": {{OUTPUT_AMOUNT}}
      }
    ]' \
    > raw.hex

sign WALLET_NAME:
  bbqcoin-cli -rpcwallet={{WALLET_NAME}} signrawtransactionwithwallet `cat raw.hex` > signed.json

send:
  bbqcoin-cli sendrawtransaction `cat signed.json | jq '.hex' --raw-output`
